---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: vcenter.hpemx.lab
      username: danny@hpemx.lab
      password: HPE1nvent
      validate_certs: False
      name: testvm_2
      template: rhel7template
      datacenter: Datacenter
      folder: /
      state: poweredon
      wait_for_ip_address: yes

